#!/usr/bin/env python

"""
@author: Alexander D Leech
@date:   04/04/2018
@rev:    1
@lang:   Python 2.7
@deps:   <None>
@desc:   Assignment one
"""

# Assignment 1
# A.  Create a program that can add or subtract two numbers
#      inputted by the user and tell them the result.
#
# B.  Add the ability to subtract and multiply (Hint, you
#      should be just adding two 'functions')
#
# C.  If you have not already, comment your code.
#
# D.  When a user types exit, end the program.
#
# E.  Add the ability to use the previous calculated answer
#     by typing 'ans'
#
#
# There are a total of 14 marks avaliable, with a bonus 6 for
#  optimised code.
#
# Good luck, and remember, "Help is always given at Hogwarts
#  to those who ask for it".

print("Open source, open mind")
